stages:
  - build
  - deploy
  - site

variables:
  img: debian:bookworm-20240904-slim
  curl_img: curlimages/curl:7.83.0
  pkg_url:
    "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"

make:
  image: ${img}
  stage: build
  before_script:
    - rm -rf /var/cache/apt/archives
    - test -d archives && mv archives /var/cache/apt/
  script:
  - apt update && apt install -y --force-yes curl git unzip zip xz-utils
  - ./build.sh
  after_script:
    - mv /var/cache/apt/archives .
  cache:
    paths:
      - archives
  artifacts:
    paths:
      - momw-tools-pack-linux.tar.gz
      - momw-tools-pack-macos.zip
      - momw-tools-pack-windows.zip
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG

pages:
  stage: site
  artifacts:
    paths:
      - public
  image: ${img}
  cache:
    paths:
      - archives
  before_script:
    - rm -rf /var/cache/apt/archives
    - test -d archives && mv archives /var/cache/apt/
  script:
    - apt update && apt install -y cmark curl pandoc git
    - git submodule init
    - git submodule update
    - ./web/build.sh --profile prod
    - mv web/build public
  after_script:
    - mv /var/cache/apt/archives .
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      changes:
        - README.org
        - CHANGELOG.md
        - web/**/*

upload:
  stage: deploy
  image: ${curl_img}
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - 'curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file momw-tools-pack-linux.tar.gz "${pkg_url}/momw-tools-pack-linux.tar.gz"'
    - 'curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file momw-tools-pack-macos.zip "${pkg_url}/momw-tools-pack-macos.zip"'
    - 'curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file momw-tools-pack-windows.zip "${pkg_url}/momw-tools-pack-windows.zip"'
